### ISSUE TITLE
Strapi 5 support?

### ISSUE THREAD

**Issue by broksonic21** [notum-cz/strapi-plugin-record-locking#104]
Can we get strapi 5 support?

big fans of this plugin, but it's dependency on 4.X explicitly is holding us back from an update

Thanks!

https://github.com/notum-cz/strapi-plugin-record-locking/blob/main/package.json#L21-L29

**Comment by dominik-juriga** [comment]
Hi @broksonic21! Yes, the support for V5 is coming in the upcoming weeks. We're already working on the update and once it's tested, we'll release it as a new major version.

**Comment by dominik-juriga** [comment]
As there are no new issues, we're closing this as completed. If you have any feedback, please, feel free to open a new issue thread.
