### ISSUE TITLE
Publish new version supporting node v18

### ISSUE THREAD

**Issue by edlefebvre** [notum-cz/strapi-plugin-record-locking#18]
I can see that master branch supports node v18.

Is it possible to publish a new release so that we can use this version via npm?

Thanks

**Comment by nicolashefti** [comment]
@martincapek is it possible to release a minor version with the last commits of the repo ? This would allow node engine > 16.

Thanks in advance

**Comment by nicolashefti** [comment]
@edlefebvre you can still install the main branch like this:

`yarn add https://github.com/notum-cz/strapi-plugin-record-locking#main`

**Comment by omikulcik** [comment]
Hi, we have published a beta version that supports node v18 https://www.npmjs.com/package/@notum-cz/strapi-plugin-record-locking/v/0.3.2 There is still some a regarding the content security policies being logged to the console and we are working on fixing it and then we will publish new version

**Comment by omikulcik** [comment]
We have just published new production version of this plugin that supports Node v18 so I am closing this issue.
