### ISSUE TITLE
Question: Can the plugin store the state in redis?

### ISSUE THREAD

**Issue by Krofer** [notum-cz/strapi-plugin-record-locking#54]
I assume that at the moment the socket connection state lies inside the application. This is a problem for my project, because my application is on different replicas at the same time and because of this, sockets cannot establish the correct connection. Is such an opportunity planned?

**Comment by omikulcik** [comment]
Hi @Krofer, thank you for the question. I do not think this is something we will implement. If you want you can implement it yourself and submit a PR. Sorry for your troubles.

**Comment by Krofer** [comment]
Hi! thanks for your answer! Okay :) I will try it!
