### ISSUE TITLE
Plan to increase dependencies?

### ISSUE THREAD

**Issue by broksonic21** [notum-cz/strapi-plugin-record-locking#82]
Great plugin - thanks for doing this!

I saw there were dependabot PRs, but there are other out-of-date/insecure dependencies as well. Is there a plan to do an upgrade cycle soon and push a release? how can the community help?

**Comment by omikulcik** [comment]
I have merged the dependabot PRs and bumped Strapi as a peer dep. There are not anymore dependencies to my knowledge.

**Comment by broksonic21** [comment]
Thanks @omikulcik - confirmed this fixes a number of security warnings on the new release!
