### ISSUE TITLE
English translation suggestion

### ISSUE THREAD

**Issue by broksonic21** [notum-cz/strapi-plugin-record-locking#85]
Since we started using this more, had one suggestion for a translation for the English - change `This entry is currently edited by {username}` to `This entry is currently being edited by {username}` (i.e. adding `being`)

Put a PR in at https://github.com/notum-cz/strapi-plugin-record-locking/pull/84

**Comment by broksonic21** [comment]
thanks for merging this! thoughts on release timing?

**Comment by omikulcik** [comment]
Hi @broksonic21 Sorry for the delay. I was overwhelmed with commercial projects. I will release the new version by the end of this week. Probably today.

Thanks for contributing! :)

**Comment by broksonic21** [comment]
Thanks @omikulcik - confirmed this works on the new release!
